/*
 * This source file was generated by the Gradle 'init' task
 */
package net.portswigger;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void test() {

    }
}
